version: '3.9'
services:
    web:
        image: rmohr/activemq
        restart: unless-stopped
        ports:
            - "8161:8161"
            - "61616:61616"
        healthcheck:
            test: curl --fail http://localhost:8161 || exit 1
            interval: 20s
            retries: 5
            start_period: 20s
            timeout: 10s

    broker:
        build: broker
        environment:
            SERVER_HOST: web
        depends_on:
            -   web

    auldfellas:
        build: auldfellas
        environment:
            SERVER_HOST: web
        depends_on:
            - web
            - broker

    girlpower:
        build: girlpower
        environment:
            SERVER_HOST: web
        depends_on:
            - web
            - broker

    dodgydrivers:
        build: dodgydrivers
        environment:
            SERVER_HOST: web
        depends_on:
            - web
            - broker

    client:
        build: client
        environment:
            SERVER_HOST: web
        depends_on:
            - web
            - broker
            - auldfellas
            - girlpower
            - dodgydrivers