server:
  port: 8101

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true

spring:
  rabbitmq:
    host: localhost
  application:
    name: restaurant-service
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;trustServerCertificate=true;integratedSecurity=false;encrypt=false
    username: sa
    password: IXlogin#1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true