server:
  port: 8050

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurant/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/driver/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    reactor:
      netty: TRACE
    org:
      springframework:
        cloud:
          gateway: TRACE